### ISSUE TITLE
Change the tab name "Inspector"

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/data-inspector#8]
Hi Hernan @hernanmd 

I think it would be better if instead of inspector we name the tab as "Statistics" or "data description" "describe"...
something like that.

What do you think?

<img width="147" alt="Capture d’écran 2022-02-26 à 09 29 28" src="https://user-images.githubusercontent.com/33934979/155836251-8599b7a0-144c-4c9d-b9b4-582b8993391e.png">

**Comment by hernanmd** [comment]
Hi Jordan,
You're right Inspector is not the best name for the tab, but also "Statistics" is a bit of misleading since it allows also to view df as a table, act on some items, a small visualization, and an evaluator. "Describe" it seems like a tool to make some type of annotations, and "Data Description" is a bit long :) but also it should give the idea of evaluation/histogram visualization.
I will think a bit a better name for this.

**Comment by jordanmontt** [comment]
Thanks Hernan, I will also think for another name and I will let you know :)

**Comment by jordanmontt** [comment]
I changed it to DataFrame for the moment
